/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package battleship;

import java.awt.BorderLayout;
import java.util.ArrayList;

/**
 *
 * @author ferna
 */
public class juego extends javax.swing.JFrame {
public static settings set = Game_menu.set;
tablero tab= new tablero(set.getDificultad(),set.getModo());
tablero tab2= new tablero(set.getDificultad(),set.getModo());
public static comments cm= Game_menu.cm;
public boolean player1=true,attackturn=true;
public static Game_menu gamemenu= log.gamemenu;
public static ArrayList<users> usuarios=BATTLESHIP.username;
public static users usuarioactual=Game_menu.userlogged;
public static String usuariorival;
    /**
     * Creates new form juego
     */
    public juego(String usuariorival) {
        initComponents();
        this.usuariorival=usuariorival;
        tab.setSize(550, 550);
        tab.setLocation(0, 0);
        tablero1.add(tab,BorderLayout.CENTER);
        tablero1.revalidate();
        tablero1.repaint();
        cm.setSize(200,50);
        cm.setLocation(0, 0);
        texto.add(cm);
        texto.revalidate();
        texto.repaint();
        tab2.setSize(550, 550);
        tab2.setLocation(0, 0);
        tablero1.add(tab2,BorderLayout.CENTER);
        tablero1.revalidate();
        tablero1.repaint();
        tab.setTurno(true);
        tab2.setTurno(false);
        atacar.setVisible(false);
        playername.setText("Player: "+usuarioactual.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero1 = new javax.swing.JPanel();
        Acorazado = new javax.swing.JButton();
        portaaviones = new javax.swing.JButton();
        submarino = new javax.swing.JButton();
        destructor = new javax.swing.JButton();
        Horizontal = new javax.swing.JButton();
        Vertical = new javax.swing.JButton();
        endturn = new javax.swing.JButton();
        atacar = new javax.swing.JButton();
        texto = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        playername = new javax.swing.JTextPane();
        rendirse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout tablero1Layout = new javax.swing.GroupLayout(tablero1);
        tablero1.setLayout(tablero1Layout);
        tablero1Layout.setHorizontalGroup(
            tablero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        tablero1Layout.setVerticalGroup(
            tablero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(tablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 550, 550));
        tablero1.getAccessibleContext().setAccessibleName("");

        Acorazado.setText("Acorazado");
        Acorazado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcorazadoActionPerformed(evt);
            }
        });
        getContentPane().add(Acorazado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, -1));

        portaaviones.setText("Portaaviones");
        portaaviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaavionesActionPerformed(evt);
            }
        });
        getContentPane().add(portaaviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        submarino.setText("Submarino");
        submarino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submarinoActionPerformed(evt);
            }
        });
        getContentPane().add(submarino, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, -1, -1));

        destructor.setText("Destructor");
        destructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destructorActionPerformed(evt);
            }
        });
        getContentPane().add(destructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 670, -1, -1));

        Horizontal.setText("Horizontal");
        Horizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorizontalActionPerformed(evt);
            }
        });
        getContentPane().add(Horizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        Vertical.setText("Vertical");
        Vertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerticalActionPerformed(evt);
            }
        });
        getContentPane().add(Vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        endturn.setText("end turn");
        endturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endturnActionPerformed(evt);
            }
        });
        getContentPane().add(endturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        atacar.setBackground(new java.awt.Color(153, 0, 0));
        atacar.setText("ATACK");
        atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacarActionPerformed(evt);
            }
        });
        getContentPane().add(atacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        texto.setBackground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        texto.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 220, 450));

        playername.setText("Player: 1");
        jScrollPane1.setViewportView(playername);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 270, -1));

        rendirse.setText("Rendirse");
        rendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendirseActionPerformed(evt);
            }
        });
        getContentPane().add(rendirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 0, 102));
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tablerobg.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1001));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 1001));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcorazadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcorazadoActionPerformed
        if(tab.getTurno()){
        tab.setType("Acorazado");
        tab.setImagetype("Acorazado");}
        else if(tab2.getTurno()){
            tab2.setType("Acorazado");
            tab2.setImagetype("Acorazado");
        }
        
    }//GEN-LAST:event_AcorazadoActionPerformed

    private void portaavionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaavionesActionPerformed
        if(tab.getTurno()){
        tab.setType("Portaaviones");
        tab.setImagetype("Portaaviones");}
        else if(tab2.getTurno()){
            tab2.setType("Portaaviones");
            tab2.setImagetype("Portaaviones");
        }
    }//GEN-LAST:event_portaavionesActionPerformed

    private void submarinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submarinoActionPerformed
        if(tab.getTurno()){
        tab.setType("Submarino");
        tab.setImagetype("Submarino");}
        else if(tab2.getTurno()){
            tab2.setType("Submarino");
            tab2.setImagetype("Submarino");
        }
    }//GEN-LAST:event_submarinoActionPerformed

    private void destructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destructorActionPerformed
        if(tab.getTurno()){
        tab.setType("Destructor");
        tab.setImagetype("Destructor");}
        else if(tab2.getTurno()){
            tab2.setType("Destructor");
            tab2.setImagetype("Destructor");
        }
    }//GEN-LAST:event_destructorActionPerformed

    private void HorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorizontalActionPerformed
        if(tab.getTurno()){
        tab.setVertical(false);
        tab.setHorizontal(true);}
        else if(tab2.getTurno()){
            tab2.setVertical(false);
            tab2.setHorizontal(true);
        }
    }//GEN-LAST:event_HorizontalActionPerformed

    private void VerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerticalActionPerformed
        if(tab.getTurno()){
        tab.setHorizontal(false);
        tab.setVertical(true);}
        else if(tab2.getTurno()){
         tab2.setHorizontal(false);
        tab2.setVertical(true);   
        }
    }//GEN-LAST:event_VerticalActionPerformed

    private void endturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endturnActionPerformed
        
        if(!tab.getTurno()&&player1){
            if(tab2.attackEnded()){
              
             attackturn=false;
             tab2.setTurno(true);
            player1=false;
            playername.setText("Player: "+usuariorival);
            }
            else{
                player1=false;
            tab.setVisible(false);
            tab2.setVisible(true);
            tab2.setTurno(true);
             playername.setText("Player: "+usuariorival);}
           
            
        }
        
        else if(!tab2.getTurno()&&!player1){
            Vertical.setVisible(false);
            Horizontal.setVisible(false);
            Acorazado.setVisible(false);
            portaaviones.setVisible(false);
            submarino.setVisible(false);
            destructor.setVisible(false);
            atacar.setVisible(true);
           
            if(tab.attackEnded()){
                
            attackturn=true;
            tab.setTurno(true);
            player1=true;playername.setText("Player: "+usuarioactual.getName());
            }
            else{
            tab2.setVisible(false);
            tab.setVisible(true);
            player1=true;
            tab.setTurno(true);
            playername.setText("Player: "+usuarioactual.getName());
            }
            
            
        }
        
       
        
    }//GEN-LAST:event_endturnActionPerformed

    private void atacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atacarActionPerformed
        if(tab.getTurno()){
          tab2.setBombardeo(true);
             
            
            tab.setVisible(false);
            tab2.setVisible(true);
            player1=true;
            tab.setTurno(false);
            
        }
        else if(tab2.getTurno()){
            
            tab.setBombardeo(true);
           
             
            tab2.setVisible(false);
            tab.setVisible(true);
            player1=false;
            tab2.setTurno(false);
       }
    }//GEN-LAST:event_atacarActionPerformed

    private void rendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendirseActionPerformed
        this.dispose();
        gamemenu.setVisible(true);
                
    }//GEN-LAST:event_rendirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new juego(usuariorival).setVisible(true);
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acorazado;
    private javax.swing.JButton Horizontal;
    private javax.swing.JButton Vertical;
    private javax.swing.JButton atacar;
    private javax.swing.JButton destructor;
    private javax.swing.JButton endturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane playername;
    private javax.swing.JButton portaaviones;
    private javax.swing.JButton rendirse;
    private javax.swing.JButton submarino;
    private javax.swing.JPanel tablero1;
    private javax.swing.JScrollPane texto;
    // End of variables declaration//GEN-END:variables
}
